apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: shortlink
  labels:
    dashboards: "grafana"
spec:
  config:
    log:
      mode: "console"

    auth:
      disable_login_form: "false"

      anonymous:
        enabled: true

        # Organization name that should be used for unauthenticated users
        org_name: "Main Org."

        # Role for unauthenticated users, other valid values are `Editor` and `Admin`
        org_role: Viewer

        # Hide the Grafana version text from the footer and help tooltip for unauthenticated users (default: false)
        hide_version: true

    security:
      admin_user: root
      admin_password: secret

  deployment:
    spec:
      template:
        spec:
          containers:
            - name: grafana
              image: grafana/grafana:11.0.0-preview
              securityContext:
                allowPrivilegeEscalation: true
                readOnlyRootFilesystem: false
              readinessProbe:
                failureThreshold: 3
