apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.alloy.alloy.configMap.name }}
  labels:
    app.kubernetes.io/name: alloy
data:
  {{ .Values.alloy.alloy.configMap.key | default "config.alloy" }}: |-
    {{- include "alloy.config" . | nindent 4 }}
