apiVersion: v1
kind: ConfigMap
metadata:
  name: external-gateway-options
data:
  service: |
    spec:
      type: NodePort
      ports:
        - name: status-port
          port: 15021
          protocol: TCP
          targetPort: 15021
          nodePort: 15021
        - name: http
          port: 80
          protocol: TCP
          targetPort: 80
          nodePort: 80
        - name: https
          port: 443
          protocol: TCP
          targetPort: 443
          nodePort: 443
