apiVersion: v1
kind: ConfigMap
metadata:
  name: external-gateway-options
data:
  deployment: |
    spec:
      template:
        spec:
          hostNetwork: true
          dnsPolicy: ClusterFirstWithHostNet
          securityContext:
            sysctls: []
  service: |
    spec:
      type: ClusterIP
