{{/* vim: set filetype=mustache: */}}

{{- define "shortlink-common.HPA" }}
{{- if and .Values.hpa.enabled -}}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  {{- include "shortlink-common.metadata" . }}
spec:
  {{- with .Values.hpa.spec }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  minReplicas: {{ .Values.hpa.minReplicas | default 1 }}
  maxReplicas: {{ .Values.hpa.maxReplicas | default 5 }}
  scaleTargetRef:
    {{- include "shortlink-common.deploymentType" . | nindent 4 }}
    name: {{ include "helpers.fullname" . }}
  metrics:
    {{- toYaml .Values.hpa.metrics | nindent 4 }}
{{- end }}
{{- end }}
