argo-workflows:
  enabled: true

  fullnameOverride: argo-workflows

  controller:
    metricsConfig:
      enabled: true
    telemetryConfig:
      enabled: true
    serviceMonitor:
      enabled: true
      additionalLabels:
        release: prometheus-operator

    workflowNamespaces: []

    # -- enable persistence using postgres
    # postgresql:
    #  host: localhost
    #  port: 5432
    #  database: argo
    #  tableName: argo_workflows

    logging:
      format: "json"

    resources:
      limits:
        cpu: 1000m
        memory: 1024Mi
      requests:
        cpu: 100m
        memory: 128Mi

  server:
    revisionHistoryLimit: 4

    baseHref: /

    ingress:
      # TODO: enable when fix SSO
      # -> ofr sso  need open and setting dex handler /api/dex
      enabled: false

      ingressClassName: nginx

      annotations:
        cert-manager.io/cluster-issuer: cert-manager-production
        nginx.ingress.kubernetes.io/backend-protocol: HTTP
        nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
        nginx.ingress.kubernetes.io/enable-opentelemetry: "true"

      hosts:
        - workflows.shortlink.best

      paths:
        - /

      tls:
        - secretName: workflows-argo-ingress-tls
          hosts:
            - workflows.shortlink.best

    logging:
      format: "json"

    secure: true

    authModes:
      - server
      # TODO: enable when fix SSO
      # - sso

    sso:
      # TODO: enable when fix SSO
      enabled: false
      issuer: https://argo.shortlink.best/api/dex
      sessionExpiry: 240h
      rbac:
        enabled: true
      scopes:
        - groups
      clientId:
        name: argo-workflows-sso
        key: client-id
      clientSecret:
        name: argo-workflows-sso
        key: client-secret
      redirectUrl: https://workflows.shortlink.best/oauth2/callback
