apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: shortlink-template
spec:
  serviceAccountName: argo
  templates:
    - name: templateContainer
      inputs:
        parameters:
          - name: message
      container:
        image: docker/whalesay:latest
        command: [ cowsay ]
        args: [ "{{ printf "{{inputs.parameters.message}}" }}" ]
        resources: # limit the resources
          limits:
            memory: 32Mi
            cpu: 100m
      retryStrategy:
        limit: 10
        retryPolicy: "Always"
        backoff:
          duration: "1"      # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"
          factor: 2
          maxDuration: "1m"  # Must be a string. Default unit is seconds. Could also be a Duration, e.g.: "2m", "6h", "1d"
        affinity:
          nodeAntiAffinity: { }
