apiVersion: v2
appVersion: "1.0.0"
name: grafana-alloy
version: 0.2.2
kubeVersion: ">= 1.30.0 || >= v1.30.0-0"
keywords:
  - grafana
  - observability
maintainers:
  - email: batazor111@gmail.com
    name: batazor
    url: batazor.ru
engine: gotpl
type: application
deprecated: false
dependencies:
  - name: alloy
    version: 1.2.1
    repository: https://grafana.github.io/helm-charts
    condition: alloy.enabled
    tags:
      - monitoring

