alloy:
  fullnameOverride: grafana-alloy

  stabilityLevel: experimental

  serviceMonitor:
    enabled: true

    additionalLabels:
      release: prometheus-operator

  alloy:
    configMap:
      create: false
      name: alloy-config
      key: config.alloy

