alloy:
  alloy:
    fullnameOverride: grafana-alloy

    stabilityLevel: experimental

    serviceMonitor:
      enabled: true

      additionalLabels:
        release: prometheus-operator

    extraPorts:
      - name: otlp-grpc
        port: 4317
        targetPort: 4317
      - name: otlp-http
        port: 4318
        targetPort: 4318

    configMap:
      create: false
      name: alloy-config
      key: config.alloy

