apiVersion: v1
kind: ConfigMap
metadata:
  name: shop-grafana-dashboard
  labels:
    grafana_dashboard: "true"
  annotations:
    grafana_dashboard_folder: Shop
data:
  shop-grafana-dashboard.json.url: "https://raw.githubusercontent.com/shortlink-org/shortlink/main/ops/Helm/shortlink-shop/admin/files/shop-grafana-dashboard.json"
