# Common default values for signadot.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

auth:
  enabled: false

zot:
  enabled: true

  service:
    type: ClusterIP

  ingress:
    enabled: true

    annotations:
      cert-manager.io/cluster-issuer: cert-manager-production
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
      nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
      nginx.ingress.kubernetes.io/enable-opentelemetry: "true"

    hosts:
      - host: zot.shortlink.best
        paths:
          - path: /

    tls:
      - hosts:
        - zot.shortlink.best
        secretName: zot-signadot-tls

  mountConfig: true
  configFiles: false
