promtail:
  enabled: true

  # this is required so that the promtail process can read the kube-apiserver audit logs written as `nobody` user
  containerSecurityContext:
    capabilities:
      add:
        - DAC_READ_SEARCH

  extraVolumes:
    - name: audit-logs
      hostPath:
        path: /var/log/audit/kube

  extraVolumeMounts:
    - name: audit-logs
      mountPath: /var/log/audit/kube
      readOnly: true

  config:
    clients:
      - url: http://grafana-loki:3100/loki/api/v1/push

    logFormat: json
    enableTracing: true

    snippets:
      extraScrapeConfigs: |
        - job_name: auditlogs
          static_configs:
            - targets:
                - localhost
              labels:
                job: auditlogs
                host: ${HOSTNAME}
                __path__: /var/log/audit/kube/*.log 

  networkPolicy:
    enabled: false

  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 64Mi

  serviceMonitor:
    enabled: true

    labels:
      release: prometheus-operator

    prometheusRule:
      enabled: true
      rules:
        - alert: PromtailRequestErrors
          expr: 100 * sum(rate(promtail_request_duration_seconds_count{status_code=~"5..|failed"}[1m])) by (namespace, job, route, instance) / sum(rate(promtail_request_duration_seconds_count[1m])) by (namespace, job, route, instance) > 10
          for: 5m
          labels:
            severity: critical
          annotations:
            description: |
              The {{"{{"}} $labels.job {{"}}"}} {{"{{"}} $labels.route {{"}}"}} is experiencing
              {{"{{"}} printf \"%.2f\" $value {{"}}"}} errors.
              VALUE = {{"{{"}} $value {{"}}"}}
              LABELS = {{"{{"}} $labels {{"}}"}}
            summary: Promtail request errors (instance {{"{{"}} $labels.instance {{"}}"}})
        - alert: PromtailRequestLatency
          expr: histogram_quantile(0.99, sum(rate(promtail_request_duration_seconds_bucket[5m])) by (le)) > 1
          for: 5m
          labels:
            severity: critical
          annotations:
            summary: Promtail request latency (instance {{"{{"}} $labels.instance {{"}}"}})
            description: |
              The {{"{{"}} $labels.job {{"}}"}} {{"{{"}} $labels.route {{"}}"}} is experiencing
              {{"{{"}} printf \"%.2f\" $value {{"}}"}}s 99th percentile latency.
              VALUE = {{"{{"}} $value {{"}}"}}
              LABELS = {{"{{"}} $labels {{"}}"}}
