{{/* vim: set filetype=mustache: */}}

{{- define "shortlink-common.metadata" }}
  name: {{ .name | default (include "helpers.fullname" .) }}
  labels:
    {{- with .Values.commonLabels }}
      {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    {{- include "helpers.labels" . | nindent 4 }}
  {{- with .Values.annotations }}
  annotations:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
{{- end }}
