apiVersion: executor.testkube.io/v1
kind: Executor
metadata:
  name: cypress-v12-executor
  namespace: testkube
spec:
  image: kubeshop/testkube-cypress-executor:1.14.0-cypress12   # <-- we're building cypress versions
  types:
    - cypress:v12/test # <-- just create different test type with naming convention "framework:version/type"
