{{/* vim: set filetype=mustache: */}}

{{- define "shortlink-common.NetworkPolicy" }}
{{- if and .Values.networkPolicy .Values.networkPolicy.enabled (or (not .Values.networkPolicy.type) (eq .Values.networkPolicy.type "system")) }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  {{- include "shortlink-common.metadata" . }}
spec:
  podSelector:
    matchLabels:
      {{- include "shortlink-common.matchLabels" . | indent 6 }}
  egress:
    {{- range .Values.networkPolicy.egress }}
    - ports:
        {{- range .ports }}
        - port: {{ .port }}
          protocol: {{ .protocol }}
        {{- end }}
      to:
        {{- range .to }}
        - namespaceSelector:
            matchLabels:
              {{- range .namespaceSelector }}
              {{ .key }}: {{ .value }}
              {{- end }}
          podSelector:
            {{- with .podSelector }}
            matchLabels:
              {{- range . }}
              {{ .key }}: {{ .value }}
              {{- end }}
            {{- end }}
        {{- end }}
    {{- end }}
  ingress:
    {{- range .Values.networkPolicy.ingress }}
    - from:
      {{- range .from }}
      {{- if .namespaceSelector }}
        - namespaceSelector:
            {{- toYaml .namespaceSelector | nindent 12 }}
      {{- end }}
      {{- if .podSelector }}
        - podSelector:
            {{- toYaml .podSelector | nindent 12 }}
      {{- end }}
      {{- if .ports }}
      ports:
        {{- range .ports }}
        - port: {{ .port }}
          protocol: {{ .protocol }}
        {{- end }}
      {{- end }}
      {{- end }}
    {{- end }}
  policyTypes:
    {{- if .Values.networkPolicy.policyTypes }}
    {{- toYaml .Values.networkPolicy.policyTypes | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
