# Common default values for grafana.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

oncall:
  enabled: true

  base_url: grafana.shortlink.best

  engine:
    resources:
      limits:
        cpu: 1000m
        memory: 512Mi
      requests:
        cpu: 150m
        memory: 128Mi

  migrate:
    enabled: true

    annotations:
      argocd.argoproj.io/hook: Sync
      argocd.argoproj.io/hook-delete-policy: HookSucceeded

    resources:
      limits:
        cpu: 2000m
        memory: 512Mi
      requests:
        cpu: 1000m
        memory: 128Mi

  celery:
    resources:
      limits:
        cpu: 200m
        memory: 512Mi
      requests:
        cpu: 15m
        memory: 50Mi

  ingress:
    enabled: false

    annotations:
      cert-manager.io/cluster-issuer: cert-manager-production
      nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
      nginx.ingress.kubernetes.io/enable-opentelemetry: "true"

    extraPaths:
      - path: "/*"
        pathType: Prefix
        backend:
          service:
            name: ssl-redirect
            port:
              name: use-annotation

  ingress-nginx:
    enabled: false

  cert-manager:
    enabled: false

  database:
    type: postgresql

  postgresql:
    enabled: false

  externalPostgresql:
    host: oncall-postgres-ha.grafana-oncall
    port: 5432
    db_name: oncall
    user: oncall
    password:
    # Use an existing secret for the database password
    existingSecret: oncall-postgres-pguser-oncall
    # The key in the secret containing the database password
    passwordKey: password

  mariadb:
    enabled: false

  rabbitmq:
    enabled: false

  externalRabbitmq:
    host: rabbitmq.grafana
    port: 5672

    existingSecret: grafana-rabbitmq-default-user
    passwordKey: password
    usernameKey: username

  redis:
    enabled: false

  externalRedis:
    host: redis-master.grafana-oncall
    existingSecret: redis
    passwordKey: redis-password

  grafana:
    enabled: false

  externalGrafana:
    url: https://grafana.shortlink.best

  oncall: {}
    #slack:
    #  enabled: true
    #  commandName: oncall
    #  clientId: ~
    #  clientSecret: ~
    #  signingSecret: ~
    #  existingSecret: ""
    #  clientIdKey: ""
    #  clientSecretKey: ""
    #  signingSecretKey: ""
    #  redirectHost: ~
