{{/* vim: set filetype=mustache: */}}

{{- define "shortlink-common.Ingress" }}
{{- if and .Values.ingress.enabled }}
---
{{- if (eq .Values.ingress.ingressClassName "istio") -}}
{{ template "shortlink-common.istioIngress" . }}
{{- else -}}
{{ template "shortlink-common.defaultIngress" . }}
{{- end }}
{{- end }}
{{- end }}
