{{/* vim: set filetype=mustache: */}}

{{- define "shortlink-common.defaultIngress" }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ empty .Values.ingress.name | ternary (include "helpers.fullname" .) .Values.ingress.name }}
  labels:
    {{- include "helpers.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.ingress.spec }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  ingressClassName: {{ .Values.ingress.ingressClassName | default "nginx" }}
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - http:
        paths:
          {{- range .Values.ingress.paths }}
          - path: {{ .path }}
            pathType: {{ default "Prefix" .pathType }}
            backend:
              service:
                name: {{ .service.name }}
                port:
                  number: {{ .service.port }}
          {{- end }}
      {{- if .Values.ingress.hostname }}
      host: {{ .Values.ingress.hostname }}
      {{- end }}
{{- end }}
