{{/* vim: set filetype=mustache: */}}

{{- define "shortlink-common.gateway" }}
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  {{ .name | default (include "helpers.fullname" .) }}-gateway
spec:
  infrastructure:
    labels:
      app.kubernetes.io/name: hello-world
{{- end }}
