loki:
  enabled: true

  nameOverride: grafana-loki

  deploymentMode: SingleBinary

  loki:
    revisionHistoryLimit: 3

    auth_enabled: false

    commonConfig:
      replication_factor: 1

    storage:
      type: filesystem

    schemaConfig:
      configs:
        - from: 2024-04-01
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h

    structuredConfig:
      query_range:
        align_queries_with_step: true

      memberlist:
        bind_addr: []

  test:
    enabled: false

  write:
    replicas: 0

    persistence:
      storageClass: local-path

    resources:
      limits:
        cpu: 300m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 64Mi

  read:
    replicas: 0

    persistence:
      storageClass: local-path

    resources:
      limits:
        cpu: 300m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 64Mi

  singleBinary:
    replicas: 1

    extraArgs:
      - --pattern-ingester.enabled=true

    persistence:
      storageClass: local-path

    resources:
      limits:
        cpu: 300m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 64Mi

  monitoring:
    dashboards:
      enabled: true
      annotations:
        grafana_dashboard_folder: Loki

    serviceMonitor:
      enabled: true
      labels:
        release: prometheus-operator

    selfMonitoring:
      grafanaAgent:
        installOperator: false

    rules:
      enabled: true
      additionalGroups:
        - name: additional-loki-rules
          rules:
            - record: job:loki_request_duration_seconds_bucket:sum_rate
              expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job)
            - record: job_route:loki_request_duration_seconds_bucket:sum_rate
              expr: sum(rate(loki_request_duration_seconds_bucket[1m])) by (le, job, route)
            - record: node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate
              expr: sum(rate(container_cpu_usage_seconds_total[1m])) by (node, namespace, pod, container)

  lokiCanary:
    enabled: false

  gateway:
    enabled: false

    resources:
      limits:
        cpu: 300m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 64Mi

  sidecar:
    resources:
      limits:
        cpu: 300m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 64Mi

  backend:
    replicas: 0

    resources:
      limits:
        cpu: 300m
        memory: 1Gi
      requests:
        cpu: 50m
        memory: 64Mi

  tracing:
    enabled: true
    jaegerAgentHost: grafana-tempo.grafana:6831
