# Common default values for rabbitmq-cluster-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

secret:
  read:
    - shortlink

rabbitmq:
  clusterName: shortlink

rabbitmq-cluster-operator:
  enabled: true

  fullnameOverride: rabbitmq

  clusterOperator:
    # disabled because we have issue: https://github.com/bitnami/charts/issues/7879
    metrics:
      service:
        enabled: true

      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-operator

  msgTopologyOperator:
    metrics:
      service:
        enabled: true

      serviceMonitor:
        enabled: true
        additionalLabels:
          release: prometheus-operator

ingress:
  enabled: true
  ingressClassName: nginx
  annotations:
    cert-manager.io/cluster-issuer: cert-manager-production
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/use-regex: "true"

  hostname: shortlink.best
  paths:
    - path: /rabbitmq/?(.*)
      service:
        name: shortlink
        port: 15672
