apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: crunchy-postgres-exporter
spec:
  namespaceSelector:
    matchNames:
      - postgres-operator
      - shortlink
  selector:
    matchLabels:
      postgres-operator.crunchydata.com/crunchy-postgres-exporter: "true"
  podTargetLabels:
    - deployment
    - role
    - pg_cluster
  podMetricsEndpoints:
    - port: exporter
      path: /metrics
      honorLabels: true
      interval: 10s
      relabelings:
        - action: drop
          regex: '5432'
          sourceLabels:
            - __meta_kubernetes_pod_container_port_number
        - action: drop
          regex: '8009'
          sourceLabels:
            - __meta_kubernetes_pod_container_port_number
        - action: drop
          regex: '2022'
          sourceLabels:
            - __meta_kubernetes_pod_container_port_number
        - action: drop
          regex: '10000'
          sourceLabels:
            - __meta_kubernetes_pod_container_port_number
        - action: replace
          sourceLabels:
            - __meta_kubernetes_namespace
          targetLabel: kubernetes_namespace
        - action: replace
          sourceLabels:
            - __meta_kubernetes_pod_name
          targetLabel: pod
        - action: replace
          replacement: $1$2
          separator: ':'
          sourceLabels:
            - __meta_kubernetes_namespace
            - >-
              __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_cluster
          targetLabel: pg_cluster
        - action: replace
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_ip
          targetLabel: ip
        - action: replace
          replacement: $1
          sourceLabels:
            - >-
              __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_instance
          targetLabel: deployment
        - action: replace
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_label_postgres_operator_crunchydata_com_role
          targetLabel: role
        - action: replace
          replacement: $1
          sourceLabels:
            - dbname
          targetLabel: dbname
        - action: replace
          replacement: $1
          sourceLabels:
            - relname
          targetLabel: relname
        - action: replace
          replacement: $1
          sourceLabels:
            - schemaname
          targetLabel: schemaname
        - action: replace
          replacement: pg
          targetLabel: exp_type
