{{/* vim: set filetype=mustache: */}}


{{/*
# `shortlink-common.service` Helm Template
#
# Overview:
# This template generates a Kubernetes Service resource configured according to the
# settings provided in the chart's `values.yaml` file. It supports defining multiple ports,
# setting the service type, and customizing IP family policies.
#
# Configuration (`values.yaml`):
# To configure the service, specify details under the `service` key in `values.yaml`.
# Include service type, spec options, ports configuration, and any desired labels or annotations.
#
# Example `values.yaml` configuration:
# service:
#   type: ClusterIP
#   spec: {}
#   ports:
#     - name: http
#       port: 80
#       targetPort: http
#       protocol: TCP
#       appProtocol: http
#       public: true
#   # Optional: Define NodePort if service.type is NodePort
#   #   nodePort: 30000
#
# Usage:
# Include this template in your Helm chart to create a Service resource based on the configurations
# provided in `values.yaml`. This template automatically integrates with `shortlink-common.metadata`
# for consistent labeling and annotation practices.
*/}}

{{- define "shortlink-common.service" }}
{{- if gt (len .Values.service.ports) 0 }}
---
apiVersion: v1
kind: Service
metadata:
  {{- include "shortlink-common.metadata" . | indent 2 }}
spec:
  {{- with .Values.service.spec }}
    {{- toYaml . | nindent 2 }}
  {{- end }}
  type: {{ .Values.service.type | default "ClusterIP" }}
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
  ports:
    {{- range .Values.service.ports }}
    {{- if .public }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .name }}
      protocol: {{ .protocol }}
      # kubectl explain Service.spec.ports.appProtocol
      appProtocol: {{ .appProtocol }}
      {{- if (and (eq $.Values.service.type "NodePort") (not (empty .nodePort))) }}
      nodePort: {{.nodePort}}
      {{- end -}}
      # TODO: use after upgrade to v1.31
      {{/* trafficDistribution: {{ .Values.service.trafficDistribution | default "PreferClose" }} */}}
    {{- end -}}
    {{- end }}
  selector:
    {{- include "shortlink-common.matchLabels" . | indent 4 }}
{{- end }}
{{- end }}

{{- define "shortlink-common.Service" }}

{{- include "shortlink-common.service" . }}
---

{{- if eq .Values.deploy.type "Rollout" -}}
{{ $test := . | deepCopy }}
{{ $_ := set $test "name" (printf "%s-%s" (include "helpers.fullname" .) "preview") }}
{{- include "shortlink-common.service" $test }}
{{- end }}
{{- end }}
