# Common default values for vector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

vector:
  enabled: true

  role: Agent

  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 256Mi

  podMonitor:
    enabled: true

  customConfig:
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: false
    sources:
      kubernetes_logs:
        type: kubernetes_logs
        # use_apiserver_cache: true
      host_metrics:
        filesystem:
          devices:
            excludes: [ binfmt_misc ]
          filesystems:
            excludes: [ binfmt_misc ]
          mountpoints:
            excludes: [ "*/proc/sys/fs/binfmt_misc" ]
        type: host_metrics
      internal_metrics:
        type: internal_metrics
#    transforms:
#      kubernetes_format:
#        type: remap
#        inputs: ["kubernetes_logs"]
#        source: |
#          ., err = parse_json(.message)
    sinks:
      prom_exporter:
        type: prometheus_exporter
        inputs: [ host_metrics, internal_metrics ]
        address: 0.0.0.0:9090
      loki:
        type: loki
        inputs: ["kubernetes_logs"]
        encoding:
          codec: native_json
        compression: snappy
        remove_label_fields: true
        remove_timestamp: true
        endpoint: http://grafana-loki.grafana:3100
        labels:
          "pod_labels_*": |-
            {{ print "{{ kubernetes.pod_labels }}" }}
          "*": |-
            {{ print "{{ metadata }}" }}
