apiVersion: opentelemetry.io/v1beta1
kind: Instrumentation
metadata:
  name: dotnet-instrumentation
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  exporter:
    endpoint: http://otel-collector-collector.grafana.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: always_on
  dotnet:
    env:
      - name: OTEL_DOTNET_AUTO_TRACES_GRPCNETCLIENT_INSTRUMENTATION_ENABLED
        value: 'true'
      - name: OTEL_DOTNET_AUTO_METRICS_PROCESS_INSTRUMENTATION_ENABLED
        value: 'true'
