apiVersion: opentelemetry.io/v1beta1
kind: Instrumentation
metadata:
  name: go-instrumentation
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  exporter:
    endpoint: http://otel-collector-collector.grafana.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: always_on
  go:
    env: []
