apiVersion: opentelemetry.io/v1beta1
kind: Instrumentation
metadata:
  name: java-instrumentation
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  exporter:
    endpoint: http://otel-collector-collector.grafana.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: always_on
  java:
    env:
      - name: OTEL_INSTRUMENTATION_KAFKA_ENABLED
        value: 'true'
      - name: OTEL_INSTRUMENTATION_REDISCALA_ENABLED
        value: 'true'
