apiVersion: opentelemetry.io/v1beta1
kind: Instrumentation
metadata:
  name: python-instrumentation
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  exporter:
    endpoint: http://otel-collector-collector.grafana.svc.cluster.local:4318
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: always_on
  dotnet:
    env:
      - name: OTEL_LOGS_EXPORTER
        value: otlp_proto_http
      - name: OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED
        value: 'true'
