argo-rollouts:
  enabled: true

  fullnameOverride: argo-rollouts

  controller:
    replicas: 1

    trafficRouterPlugins:
      trafficRouterPlugins: |-
        - name: "argoproj-labs/gatewayAPI"
          location: "https://github.com/argoproj-labs/rollouts-plugin-trafficrouter-gatewayapi/releases/download/v0.3.0/gateway-api-plugin-linux-amd64"

    resources:
      limits:
        cpu: 300m
        memory: 2Gi
      requests:
        cpu: 30m
        memory: 50Mi

  metrics:
    enabled: true
    serviceMonitor:
      enabled: true
