auth:
    github:
        clientid: ENC[AES256_GCM,data:nHS9TaVe2xsnrAvz5VtsSVwjLR4=,iv:9h3hiL3jrAD2Gj2cwPH86z+Id5s6txs3a73Z+I6cDds=,tag:zF7tbxtC10wMOmICmZzb/w==,type:str]
        clientsecret: ENC[AES256_GCM,data:ZB4Zwp4GHlTza8p4ErxMEZbKMeE9oQvnFHEl20AhrcFrHYAjKB4GUw==,iv:G/F0SvsgAJHL1t2Kv4tBF2KLDmOA5juc0+oW3psnc0c=,tag:ly0INjTTZJxyX1AuX/LPnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-22T13:54:26Z"
    mac: ENC[AES256_GCM,data:fv6RRUC1JJxaCN5zSVbeTg4G6GdJBgXOvHwPI5+XDzvrhyLFccJPQqOcB+y3HbwI6Vl4R5QYzFIAUI+AbN44+xs1CQvNwcgyLsMsZw1nDTvLuKOJDSFGkYcOMFzeeg4vQyzj0QK+dkMOr3To3qucTv7umcdjtjGRqjux3QR4rdE=,iv:rRTgAQG+cdUsTq6XBOYSdULeQsh6iO60Q/CEhCcLkiQ=,tag:cgich6zCR7meHPlg5WnYLA==,type:str]
    pgp:
        - created_at: "2024-06-22T13:53:22Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxDrDE6S/SFjAQv5AeUqPVu1gWBh57ACRvvwi5DDWkONmKC6JmoPTR6iKLNn
            juLIhFVtrWPGjl50crZOgDj4hvEuex1bZR7mHh7QdboaQJIxDNDFgrLvL40JXj3d
            LV2KpfRpSiOu8XgnNuTOL9m4MqVSQpsfC1+kU7JmwR7I6x7lTXdih9fhOaq7u6zR
            OXfinbscje1sExdXKPZdpqbMVJ1o3JkQdcGl2ZBmqg3Ljazg81ujTB7vK1RFToQx
            TMfellICpPfut+yISuOzpgMUbi1klLxdPq5re61cre93TyUIAk433hWBsphe57EW
            ZCFGz38LLrUUrLkOY0PkDzVdmsU02ab1rikDJIYabR/lwUPzvP7uaj9LdWsQ5+PN
            5qbG9cyqQEKjJROfsJlQ4x9RAjJ3blcJdreD7otpeWWti4kiQof4sm1lPYcfkgRw
            BFWOGxnYc7k+eE06yyeBXzp9PKf6sU5zU8jqpftv/mWKeU7ZwqDpivdg36CK5jsK
            2C/3W2LtSoLoT3ZllGaj1GYBCQIQt2wNtYIRDylYVBYnfQ+EPTyxU3wA799ROMtx
            UgBrvt0xzNNoy3dnppxoxo2Lk/LsazVXvJYze2+8D3NUlba3ewFdv68gSJzE33Rj
            41v9eq5YNsMoH2N96kE+JwKbx8eXF3Q=
            =AC3B
            -----END PGP MESSAGE-----
          fp: C92AE33AF20998F8CA09E819A842078E859DE4F1
    unencrypted_suffix: _unencrypted
    version: 3.8.1
