apiVersion: v1
kind: Secret
metadata:
  name: pyroscope-datasources
  labels:
    grafana_datasource: 'true' # default value for: sidecar.datasources.label
stringData:
  tempo.yaml: |-
    apiVersion: 1
    datasources:
      - name: Pyroscope
        type: grafana-pyroscope-datasource
        uid: pyroscope
        url: http://pyroscope.pyroscope:4040
        editable: false
