# Common default values for tracetest.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tracetest:
  postgresql:
    enabled: true

    global:
      storageClass: local-path

    volumePermissions:
      enabled: true

    serviceAccount:
      create: true

    metrics:
      enabled: true

      serviceMonitor:
        enabled: true
        labels:
          release: prometheus-operator

      prometheusRule:
        enabled: true
        labels:
          release: prometheus-operator

    primary:
      persistence:
        storageClass: local-path
        size: 1Gi

  telemetry:
    exporters:
      collector:
        exporter:
          collector:
            endpoint: http://grafana-tempo.grafana:4317

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: cert-manager-production
      nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
      nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
    hosts:
      - host: tracetest.shortlink.best
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls:
      - secretName: tracetest-tls
        hosts:
          - tracetest.shortlink.best

  resources:
    limits:
      cpu: 300m
      memory: 512Mi
    requests:
      cpu: 10m
      memory: 126Mi

  provisioning: |-
    type: DataStore
    spec:
      name: Grafana Tempo
      type: tempo
      default: true
      tempo:
        type: http
        http:
          url: http://grafana-tempo.grafana:3100
          tls:
            insecure: true
    ---
    type: Test
    spec:
      id: dSzgkfKIR
      name: "API: get links"
      trigger:
        type: http
        httpRequest:
          method: GET
          url: https://shortlink.best/api/links
          headers:
            - key: Content-Type
              value: application/json
    ---
    type: TestSuite
    spec:
      id: 2e3YoYKSR
      name: shortlink-link
      description: Link boundary
      steps:
        - dSzgkfKIR
