apiVersion: minio.min.io/v2
kind: Tenant
metadata:
  name: shortlink
scheduler:
  name: ""
spec:
  configuration:
    name: shortlink-configuration
  exposeServices:
    console: true
    minio: true
  mountPath: /export
  pools:
  - name: pool-0
    resources:
      limits:
        memory: 8Gi
      requests:
        memory: 2Gi
    servers: 4
    volumeClaimTemplate:
      metadata:
        name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: "2684354560"
        storageClassName: local-path
    volumesPerServer: 1
  prometheusOperator: true
  requestAutoCert: false
  users:
  - name: shortlink-user
  - name: testkube-user
