apiVersion: v1
kind: ConfigMap
metadata:
  name: erlang-distribution-dashboard
  labels:
    grafana_dashboard: "true"
  annotations:
    grafana_dashboard_folder: RabbitMQ
data:
  # https://grafana.com/grafana/dashboards/11352
  erlang-distribution-dashboard.json.url: "https://raw.githubusercontent.com/rabbitmq/rabbitmq-server/main/deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-Distribution.json"
