apiVersion: v1
kind: ConfigMap
metadata:
  name: erlang-distributions-compare-dashboard
  labels:
    grafana_dashboard: "true"
  annotations:
    grafana_dashboard_folder: RabbitMQ
data:
  # https://grafana.com/grafana/dashboards/10988
  erlang-distributions-compare-dashboard.json.url: "https://raw.githubusercontent.com/rabbitmq/rabbitmq-server/main/deps/rabbitmq_prometheus/docker/grafana/dashboards/Erlang-Distributions-Compare.json"
