apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-stream-dashboard
  labels:
    grafana_dashboard: "true"
  annotations:
    grafana_dashboard_folder: RabbitMQ
data:
  # https://grafana.com/grafana/dashboards/14798
  rabbitmq-stream-dashboard.json.url: "https://raw.githubusercontent.com/rabbitmq/rabbitmq-server/main/deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Stream.json"
