apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-quorum-queues-raft-dashboard
  labels:
    grafana_dashboard: "true"
  annotations:
    grafana_dashboard_folder: RabbitMQ
data:
  # https://grafana.com/grafana/dashboards/11340
  rabbitmq-quorum-queues-raft-dashboard.json.url: "https://raw.githubusercontent.com/rabbitmq/rabbitmq-server/main/deps/rabbitmq_prometheus/docker/grafana/dashboards/RabbitMQ-Quorum-Queues-Raft.json"
