apiVersion: v2
appVersion: "1.0.0"
name: pyroscope  
version: 0.1.1   
kubeVersion: ">= 1.30.0 || >= v1.30.0-0"
keywords:
  - observability
  - profiling
maintainers:
  - email: batazor111@gmail.com
    name: batazor
    url: batazor.ru
type: application
deprecated: false
dependencies:
  - name: pyroscope
    version: 2.0.1
    repository: https://grafana.github.io/helm-charts
    condition: pyroscope.enabled
    tags:
      - observability
      - profiling
