pyroscope:
  enabled: true

  extraArgs:
    log.level: info

  ingress:
    enabled: true
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: cert-manager-production
      nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
      nginx.ingress.kubernetes.io/enable-opentelemetry: "true"

    hosts:
      - pyroscope.shortlink.best

    tls:
      - secretName: shortlink-ingress-tls
        hosts:
          - pyroscope.shortlink.best

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 20m
      memory: 64Mi

  agent:
    enabled: false

  serviceMonitor:
    enabled: true

    labels:
      release: prometheus-operator

  alloy:
    enabled: false

pyroscope-ebpf:
  enabled: false

  args:
    - "ebpf"
    - "--application-name"
    - "k8s.ebpf"
    - "--server-address"
    - "http://pyroscope-server:4040"
