apiVersion: v1
kind: ConfigMap
metadata:
  name: teleport
data:
  teleport.yaml: |
    chartMode: standalone
    clusterName: teleport.shortlink.best

    teleport:
      storage:
        type: sqlite
        sync: NORMAL
        journal: WAL
        path: /storage
      log:
        severity: INFO
        output: stderr
        format:
          output: json
          extra_fields: ["timestamp","level","component","caller"]
    auth_service:
      enabled: true
      cluster_name: teleport.shortlink.best
      authentication:
        # types: local, github, gitlab
        type: local
        local_auth: true
        second_factor: "otp"
    kubernetes_service:
      enabled: true
      listen_addr: 0.0.0.0:3027
      kube_cluster_name: shortlink
    proxy_service:
      enabled: true
      public_addr: 'teleport.shortlink.best:443'
      kube_listen_addr: 0.0.0.0:3026
      mysql_listen_addr: 0.0.0.0:3036
      https_keypairs:
        - key_file: /etc/teleport-tls/tls.key
          cert_file: /etc/teleport-tls/tls.crt
    ssh_service:
      enabled: false
