# Common default values for falcosecurity.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

events:
  deletePodEvent: "{{inputs.parameters.falco-event}}"

falco:
  enabled: true

  scc:
    create: false

  collectors:
    docker:
      enabled: false
    crio:
      enabled: false

  driver:
    kind: ebpf

  falco:
    rules_file:
      - /etc/falco/falco_rules.yaml
      - /etc/falco/falco_rules.local.yaml
      - /etc/falco/rules.d
      - /etc/falco/k8s_audit_rules.yaml

    json_output: true

    grpc:
      enabled: true

    grpc_output:
      enabled: true

    metrics:
      enabled: true

  falcoctl:
    config:
      artifact:
        install:
          refs:
            - "falco-rules:2"
        follow:
          refs:
            - "falco-rules:2"

  falcosidekick:
    enabled: true

    config:
      webhook:
        address: http://webhook-falco-eventsource-svc.argocd.svc.cluster.local:12000/falco

    webui:
      enabled: false
      replicaCount: 1

      redis:
        resources:
          limits:
            cpu: 100m
            memory: 256Mi
          requests:
            cpu: 20m
            memory: 64Mi

falco-exporter:
  enabled: true

  fullnameOverride: falco-exporter

  serviceMonitor:
    enabled: true

    labels:
      release: prometheus-operator

  grafanaDashboard:
    enabled: true
    namespace: grafana
    folder: Security

  prometheusRules:
    enabled: true

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 20m
      memory: 64Mi
