apiVersion: opentelemetry.io/v1alpha1
kind: Instrumentation
metadata:
  name: nodejs-instrumentation
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  propagators:
    - tracecontext
    - baggage
  sampler:
    type: always_on
  go:
    env:
      - name: OTEL_EXPORTER_OTLP_ENDPOINT
        value: http://otel-collector-collector.grafana.svc.cluster.local:4317
