apiVersion: v2
appVersion: "1.0.0"
name: kubeshark  
version: 0.1.0   
kubeVersion: ">= 1.30.0 || >= v1.30.0-0"
keywords:
  - kubeshark
  - network
maintainers:
  - email: batazor111@gmail.com
    name: batazor
    url: batazor.ru
type: application
deprecated: false
dependencies:
  - name: kubeshark
    version: 53.2.3
    repository: https://helm.kubeshark.com
    condition: kubeshark.enabled
    tags:
      - kubeshark
      - network
