# Common default values for testkube.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

testkube:
  enabled: true

  preUpgradeHook:
    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 20m
        memory: 56Mi

  mongodb:
    enabled: false

  nats:
    enabled: true

    nats:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 20m
          memory: 56Mi

    exporter:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 20m
          memory: 56Mi

  testkube-api:
    nats:
      enabled: true

    multinamespace:
      enabled: true

    minio:
      enabled: false

    mongodb:
      dsn: "mongodb://mongodb-svc:27017"
      secretName: mongodb-testkube-testkube
      secretKey: connectionString.standard

    uiIngress:
      enabled: true
      className: nginx
      annotations:
        cert-manager.io/cluster-issuer: cert-manager-production
        nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
        nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
        nginx.ingress.kubernetes.io/auth-url: "https://testkube.shortlink.best/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://testkube.shortlink.best/oauth2/start?rd=$escaped_request_uri"
        nginx.ingress.kubernetes.io/access-control-allow-origin: "*"
      hosts:
        - testkube.shortlink.best
      path: /v1
      tlsenabled: true
      tls:
        - hosts:
            - testkube.shortlink.best
          secretName: testkube-tls

    storage:
      region: ""
      token: ""
      expiration: 0
      SSL: false
      scrapperEnabled: true

    prometheus:
      enabled: true
      monitoringLabels:
        release: prometheus-operator

    resources:
      limits:
        cpu: 500m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 200Mi

    testConnection:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 20m
          memory: 56Mi

  testkube-dashboard:
    apiServerEndpoint: "https://testkube.shortlink.best/v1"

    ingress:
      enabled: true

      className: nginx

      annotations:
        cert-manager.io/cluster-issuer: cert-manager-production
        nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
        nginx.ingress.kubernetes.io/enable-opentelemetry: "true"
        nginx.ingress.kubernetes.io/access-control-allow-origin: "*"
        nginx.ingress.kubernetes.io/auth-url: "https://testkube.shortlink.best/oauth2/auth"
        nginx.ingress.kubernetes.io/auth-signin: "https://testkube.shortlink.best/oauth2/start?rd=$escaped_request_uri"

      hosts:
        - testkube.shortlink.best

      tlsenabled: true
      tls:
        - hosts:
            - testkube.shortlink.best
          secretName: testkube-tls

    oauth2:
      enabled: true

      ingress:
        annotations:
          cert-manager.io/cluster-issuer: cert-manager-production
          nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
          nginx.ingress.kubernetes.io/enable-opentelemetry: "true"

    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 20m
        memory: 56Mi

    testConnection:
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 20m
          memory: 56Mi

  testkube-operator:
    enabled: true

    resources:
      limits:
        cpu: 100m
        memory: 100Mi
      requests:
        cpu: 20m
        memory: 56Mi

    proxy:
#      image:
#        tag: v0.15.0
      resources:
        limits:
          cpu: 100m
          memory: 100Mi
        requests:
          cpu: 20m
          memory: 56Mi

    webhook:
      enabled: true

      patch:
        enabled: true
